services:
  app:
    build:
      context: .               
      dockerfile: Dockerfile
    container_name: insta-api
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "${APP_PORT}:${APP_PORT}"  
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: myredis
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
                 --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: mypostgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: